backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
          - { label: 'Hero Title', name: 'heroTitle', widget: 'string' }
          - {
              label: 'Hero Description',
              name: 'heroDescription',
              widget: 'markdown',
            }
          - { label: 'Hero Link URL', name: 'heroLinkUrl', widget: 'string' }
          - { label: 'Hero Link Text', name: 'heroLinkText', widget: 'string' }
          - label: "Featured Recipes"
            name: 'featuredRecipes'
            widget: 'relation'
            collection: 'recipes'
            multiple: true
            searchFields: ["title"]
            valueField: "title"
  - name: 'recipes'
    label: 'Recipes'
    folder: 'content/recipes'
    create: true
    slug: "{{slug}}"
    media_folder: "public/img"
    public_folder: "img"
    editor:
      preview: false
    fields:
      - { label: 'Recipe Title', name: 'title', widget: 'string' } # Recipe title
      - { label: 'Author', name: 'author', widget: 'string' } # Author/Publication
      - { label: "Summary", name: "summary", widget: "markdown" }
      - { label: 'Dairy Free', name: 'dairyFree', widget: 'boolean' } # Dairy Free
      - { label: "Servings", name: "servings", widget: "number", default: 1, value_type: "int" } # servings
      - { label: "Prep Time", name: "prepTime", widget: "string" } # prep time
      - { label: "Cook Time" , name: "cookTime",widget: "string"} # cook time
      - { label: "Featured Image" , name: "featuredImage",widget: "image"} # image
      - label: "Ingredients" 
        name: "ingredients"
        widget: "list" 
        fields: 
          - { label: "Ingredient", name: "ingredient", widget: "string"}
      - label: "Cooking Steps"
        name: "cookingSteps"
        widget: "list"
        fields:
          - { label: "Step", name: "step", widget: "string" }
      - { label: "Cooking Instructions", name: "instructions", widget: "markdown"}
  - name: 'siteSettings'
    label: 'Site Settings'
    folder: 'content/settings'
    media_folder: 'public/img'
    public_folder: 'img'
    fields:
      - { label: 'Site Title', name: 'title', widget: 'string' }
      - { label: 'Site Logo', name: 'siteLogo', widget: 'image' }
      - label: 'Navigation Bar Links'
        name: 'navBarLinks'
        widget: 'list'
        fields:
          - { label: 'Link Text', name: 'linkText', widget: 'string'}
          - { label: 'Link URL', name: 'linkURL', widget: 'string' }